adding wasta-enable-zswap to wasta-system-upgrade

diff --git a/install-files/bin/wasta-system-upgrade b/install-files/bin/wasta-system-upgrade
--- a/install-files/bin/wasta-system-upgrade
+++ b/install-files/bin/wasta-system-upgrade
@@ -131,6 +131,19 @@ then
     fi
 fi
 
+echo
+echo "*** Running wasta-enable-zswap"
+echo
+bash wasta-enable-zswap $AUTO
+LASTERRORLEVEL=$?
+if [ "$LASTERRORLEVEL" -ne "0" ];
+then
+    echo
+    echo " *** ERROR in return from wasta-enable-zswap. Exiting."
+    echo
+    exit 1
+fi
+
 # ------------------------------------------------------------------------------
 # Finished
 # ------------------------------------------------------------------------------
